#!/usr/bin/env bash

set -euo pipefail
shopt -s expand_aliases

declare -r githubUrl='https://github.com/5ouma/homelab'
declare -r homelab="$HOME/homelab"
TMPDIR="$(mktemp -d)" && declare -r TMPDIR

export GUM_CONFIRM_SELECTED_BACKGROUND='27'
export GUM_FORMAT_THEME="$TMPDIR/blue.json"
export GUM_INPUT_CURSOR_FOREGROUND='33'
export GUM_SPIN_SPINNER_FOREGROUND='27'
export GUM_WRITE_CURSOR_FOREGROUND='33'

declare executed=false
declare skipped=false
declare goThrough=false

getGum() {
  declare -r gumVer='0.17.0'
  declare -r gumDir="gum_${gumVer}_$(uname)_$(uname -m)"
  declare -r gumUrl="https://github.com/charmbracelet/gum/releases/download/v$gumVer/$gumDir.tar.gz"
  declare -r gumThemeUrl="https://raw.githubusercontent.com/5ouma/dotfiles/main/data/blue.json"

  printf '  🚚💨 Now delivering...'
  # shellcheck disable=SC2139
  curl -sL "$gumUrl" | tar --strip-components=1 -zxC "$TMPDIR" "$gumDir/gum" && alias gumCom="$TMPDIR/gum"
  printf '\r                        '

  curl -s "$gumThemeUrl" -o "$GUM_FORMAT_THEME"
} && getGum

gum() {
  case $1 in
  confirm) gumCom confirm "$2" --affirmative="$3" --negative="$4" ;;
  format) gumCom format "${@:2}" ;;
  input) gumCom input --placeholder="$2" ;;
  style) gumCom style --foreground="$2" "${@:3}" ;;
  write) gumCom write --placeholder="$2" ;;
  executed)
    echo -en '\n  ' && gumCom format '✅ Done!'
    executed=true
    ;;
  run)
    if (tty &>/dev/null); then
      gumCom spin --title="$2" -- "${@:4}"
    else
      echo && gumCom log --level='info' "$2"
      "${@:4}"
    fi
    ;;
  skipped) echo -en '\n  ' && gumCom format '🟡 Skipped' ;;
  esac
}

alias skip='skipped=true && return'

shouldProceed() {
  ($goThrough || gum confirm 'Proceed?' 'Yes' 'No')
}

run() {
  declare -r func="$(echo "$1" | tr '[:lower:]' '[:upper:]')"
  gum format "$2"
  if (eval '${SETUP_SKIP_'"$func"':-false}'); then
    gum skipped
    return
  fi

  eval '$1'
  if ($skipped); then
    skipped=false
    gum skipped
  else
    gum executed
  fi
}

helpMsg() {
  gum format <<EOM
## Usage: setup

> 🥼 Self-hosted personal laboratory

## Commands:
-  help    Print help information

## Flags:
-  -y, --yes    Start without confirmation
EOM
}

errMsg() {
  declare -r stat=$1 func="${2/"$HOME"/~}" line=$3
  gum format <<EOM
> **$(gum style 1 'Error')**
> Unknown error has occurred!

> - Status:           $stat
> - File or Function: $func
> - Line Number:      $line
> - Process ID:       $$
EOM
} && trap 'errMsg $? "$0" $LINENO' ERR



if [[ ! -x $0 ]]; then
  gum format <<EOM
# Welcome to 🥼 Homelab setup!
> $githubUrl
---
EOM
fi

if (($# > 0)); then
  case "$1" in
  'help')
    helpMsg
    exit
    ;;
  '-y' | '--yes')
    goThrough=true
    ;;
  *)
    gum format <<EOM
> **$(gum style 1 'Error')**
> Unknown flag $1
EOM
    helpMsg
    exit 1
    ;;
  esac
fi

if (! $goThrough); then
  gum confirm "Let's start setup!" 'Yes!' 'No' || exit 1
fi

if [[ ! -d "$homelab" ]]; then
  # shellcheck disable=SC2016
  gum run 'Cloning the repository into `~/homelab`...' -- git clone "$githubUrl" "$homelab"
else
  gum run 'Pulling the homelab repository...' -- git -C "$homelab" pull
fi

sudo -v


updateSystem() {
  gum run 'Synchronizing package databases...' -- yay -Sy
  if (! yay -Qu &>/dev/null || ! shouldProceed); then
    skip
  fi

  yay -Su "$($goThrough && echo '--noconfirm')"
} && run 'updateSystem' '## 🔧 Update system'

installPackages() {
  declare -r packages=(docker docker-compose firewalld jq newrelic-infra pacman-contrib pam_ssh_agent_auth reflector tailscale)
  if (yay -Q "${packages[@]}" &>/dev/null || ! shouldProceed); then
    skip
  fi

  yay -S --needed "$($goThrough && echo '--noconfirm')" "${packages[@]}"
} && run 'installPackages' '## 📦 Install packages'

updateNewRelicInfra() {
  declare -r installed="$(yay -Q newrelic-infra | awk '{split($2, version, "-"); print version[1]}')"
  declare -r latest="$(curl -s https://api.github.com/repos/newrelic/infrastructure-agent/releases/latest | jq -r '.tag_name')"
  if [[ "$installed" == "$latest" ]] || ! shouldProceed; then
    skip
  fi

  cd "$HOME/.cache/yay/newrelic-infra"
  ./update.sh
  makepkg -sic "$($goThrough && echo '--noconfirm')"
  yay -Sc "$($goThrough && echo '--noconfirm')"
} && run 'updateNewRelicInfra' '## ⬆️ Update New Relic infrastructure agent'

enableServices() {
  declare -r services=(docker firewalld newrelic-infra paccache.timer reflector.timer sshd tailscaled)
  if (systemctl is-enabled "${services[@]}" | awk '$0 == "disabled" { exit 1 }' || ! shouldProceed); then
    skip
  fi

  gum run 'Enabling services...' -- sudo systemctl enable --now "${services[@]}"
} && run 'enableServices' '## 🎽 Enable system services'

configureReflector() {
  declare -r country="$(curl -s https://ipapi.co/country_name)"
  if (grep -q -- "--country $country" /etc/xdg/reflector/reflector.conf && grep -q -- '--sort rate' /etc/xdg/reflector/reflector.conf || ! shouldProceed); then
    skip
  fi

  gum run 'Setting auto country selection...' -- sudo sed -i "s/^# --country France,Germany/--country $country/" /etc/xdg/reflector/reflector.conf
  gum run 'Setting sorting by rate...' -- sudo sed -i 's/^--sort age/--sort rate/' /etc/xdg/reflector/reflector.conf
} && run 'configureReflector' '## 🪞 Configure Reflector'

addToDockerGroup() {
  if (groups "$USER" | grep -q docker || ! shouldProceed); then
    skip
  fi

  gum run 'Adding user to Docker group...' -- sudo usermod -aG docker "$USER"
} && run 'addToDockerGroup' '## 🐳 Add user to Docker group'

setHostname() {
  if [[ -n "$(hostnamectl status --pretty)" ]] || ! shouldProceed; then
    skip
  fi

  hostname=$(gum input 'Enter hostname')
  gum run 'Setting hostname...' -- sudo hostnamectl set-hostname "${hostname// /-}"
  gum run 'Setting pretty hostname...' -- sudo hostnamectl set-hostname --pretty "$hostname"
} && run 'setHostname' '## 🖥️ Set system hostname'

configureFirewall() {
  if (sudo firewall-cmd -q --query-service=mdns && sudo firewall-cmd -q --query-service=samba || ! shouldProceed); then
    skip
  fi

  gum run 'Adding Samba and mDNS services...' -- sudo firewall-cmd --add-service={mdns,samba} --permanent
  gum run 'Reloading firewall...' -- sudo firewall-cmd --reload
} && run 'configureFirewall' '## 🔥 Configure firewall'

configureSshKeys() {
  if [[ -f "$HOME/.ssh/authorized_keys" ]] && (grep -q 'PasswordAuthentication no' /etc/ssh/sshd_config && grep -q 'PermitRootLogin no' /etc/ssh/sshd_config || ! shouldProceed); then
    skip
  fi

  mkdir -p "$HOME/.ssh"
  gum write 'Enter SSH public key' >>"$HOME/.ssh/authorized_keys"
  gum run 'Disabling password authentication...' -- sudo sed -i 's/^#PasswordAuthentication yes/PasswordAuthentication no/' /etc/ssh/sshd_config
  gum run 'Disabling root login...' -- sudo sed -i 's/^#PermitRootLogin prohibit-password/PermitRootLogin no/' /etc/ssh/sshd_config
  gum run 'Restarting SSH service...' -- sudo systemctl restart sshd
} && run 'configureSshKeys' '## 🔑 Configure SSH keys'

configureSudoWithSshAgent() {
  declare -r sudoPam='auth sufficient pam_ssh_agent_auth.so file=~/.ssh/authorized_keys' sudoersSshEnv='Defaults env_keep += "SSH_AUTH_SOCK"'
  if (sudo grep -q "$sudoPam" /etc/pam.d/sudo && sudo grep -q "$sudoersSshEnv" /etc/sudoers || ! shouldProceed); then
    skip
  fi

  sudo grep -q "$sudoPam" /etc/pam.d/sudo || sudo sed -i "/#%PAM-*/a $sudoPam" /etc/pam.d/sudo
  sudo grep -q "$sudoersSshEnv" /etc/sudoers || echo "$sudoersSshEnv" | sudo tee -a /etc/sudoers >/dev/null
} && run 'configureSudoWithSshAgent' '## 👑 Configure sudo with SSH agent'

configureBackupDrive() {
  if (grep -q /mnt/backup /etc/fstab || ! shouldProceed); then
    skip
  fi

  sudo blkid
  backupDriveUUID="$(gum input 'Enter backup drive UUID')"
  echo "UUID=$backupDriveUUID /mnt/backup ext4 defaults 0 0" | sudo tee -a /etc/fstab >/dev/null
} && run 'configureBackupDrive' '## 💾 Configure backup drive'

configureNewRelic() {
  if [[ -f /etc/newrelic-infra/newrelic-infra.yml ]] || ! shouldProceed; then
    skip
  fi

  newRelicLicenseKey="$(gum input 'Enter New Relic license key')"
  gum run 'Creating New Relic configuration...' -- sudo tee /etc/newrelic-infra/newrelic-infra.yml >/dev/null <<EOF
license_key: $newRelicLicenseKey
display_name: $(hostnamectl status --pretty)
EOF
  gum run 'Restarting New Relic service...' -- sudo systemctl restart newrelic-infra
} && run 'configureNewRelic' '## 📊 Configure New Relic'

configureTailscale() {
  if (tailscale status &>/dev/null || ! shouldProceed); then
    skip
  fi

  sudo tailscale up --accept-routes --advertise-exit-node
  gum run 'Setting Tailscale hostname...' -- sudo tailscale set --hostname="$(hostnamectl status --pretty)"
} && run 'configureTailscale' '## 🛣️ Configure Tailscale'


if ($executed); then
  gum format '# 🎉 Homelab setup completed!'
else
  gum format '# 🧊 Nothing has changed'
fi
