name: misskey

services:
  web:
    container_name: misskey_web
    image: docker.io/misskey/misskey:2026.5.1@sha256:5c2d05623a420871fdf7d22932bacd0422244a25b334198d58d0e95e6e5816ef
    environment:
      MISSKEY_URL: $MISSKEY_URL
      DATABASE_DB: $DB_DATABASE_NAME
      DATABASE_USER: $DB_USERNAME
      DATABASE_PASSWORD: $DB_PASSWORD
    configs:
      - source: timezone
        target: /etc/localtime
      - source: misskey_config
        target: /misskey/.config/default.yml
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped

  database:
    container_name: &misskey_database misskey_database
    image: docker.io/postgres:18.3@sha256:7e32e9833a6fb1c92c32552794cb6ed569d51b445a54907d35fc112ef39684db
    environment:
      POSTGRES_HOST: $DB_HOSTNAME
      POSTGRES_DB: $DB_DATABASE_NAME
      POSTGRES_USER: $DB_USERNAME
      POSTGRES_PASSWORD: $DB_PASSWORD
    volumes:
      - database:/var/lib/postgresql
      - database-backup:/tmp/backup
    healthcheck:
      test: [CMD, pg_isready, -d, $DB_DATABASE_NAME, -U, $DB_USERNAME]
      interval: 5s
      retries: 3
    labels:
      docker-volume-backup.exec-label: *misskey_database
      docker-volume-backup.archive-pre: pg_dump -d '$DB_DATABASE_NAME' -U '$DB_USERNAME' -f /tmp/backup/misskey.sql
    restart: unless-stopped

  redis:
    container_name: misskey_redis
    image: docker.io/redis:7.2.5-alpine3.19@sha256:8f157725f8eee31e65a8d4765f1f986d76aedc1a0503345dfb63a2b1b5a441ee
    healthcheck:
      test: [CMD, redis-cli, ping]
      interval: 5s
      retries: 3
    restart: unless-stopped

  backup:
    container_name: misskey_backup
    image: docker.io/offen/docker-volume-backup:v2.48.0@sha256:8eaf987d83e7b5f7c4edd8d177c2ca74b49a0d015d241e99a260c19a043b46aa
    environment:
      BACKUP_CRON_EXPRESSION: 0 5 * * *
      BACKUP_FILENAME: misskey_database_%Y%m%d.{{ .Extension }}
      AWS_S3_PATH: $R2_PATH/database
      BACKUP_SOURCES: &backup_database_source /backup/database
      BACKUP_ARCHIVE: &backup_database_archive /archive/database
      BACKUP_RETENTION_DAYS: 14
      GPG_PASSPHRASE: $DB_PASSWORD
      EXEC_LABEL: *misskey_database
    env_file:
      - path: ../.env
        required: true
    volumes:
      - type: volume
        source: database-backup
        target: *backup_database_source
        read_only: true
      - type: bind
        source: $BACKUP_DIR/database
        target: *backup_database_archive
    configs:
      - source: docker-socket
        target: /var/run/docker.sock
      - source: timezone
        target: /etc/localtime
    depends_on:
      database:
        condition: service_healthy
    restart: unless-stopped

  cloudflare-tunnel:
    container_name: misskey_cloudflare-tunnel
    image: docker.io/cloudflare/cloudflared:2026.3.0@sha256:6b599ca3e974349ead3286d178da61d291961182ec3fe9c505e1dd02c8ac31b0
    command: [tunnel, --no-autoupdate, run]
    environment:
      TUNNEL_TOKEN: $TUNNEL_TOKEN
    restart: unless-stopped

volumes:
  database:
  database-backup:

configs:
  docker-socket:
    file: /var/run/docker.sock
  timezone:
    file: /etc/localtime
  misskey_config:
    file: ./config/misskey.yml
