name: soft-serve

services:
  server:
    container_name: soft-serve_server
    image: docker.io/charmcli/soft-serve:v0.11.6@sha256:7742f301ab4e5c24eccf999b10aabb97ec64e18c23f693a16599071d49ae5bf4
    environment:
      SOFT_SERVE_INITIAL_ADMIN_KEYS: $SOFT_SERVE_INITIAL_ADMIN_KEYS
      SOFT_SERVE_NAME: $SOFT_SERVE_NAME
      SOFT_SERVE_SSH_PUBLIC_URL: ssh://$SOFT_SERVE_DOMAIN
    volumes:
      - soft-serve:/soft-serve
    configs:
      - source: timezone
        target: /etc/localtime
      - source: git_config
        target: /root/.gitconfig
    healthcheck:
      test: [CMD, wget, --spider, -q, http://localhost:23232/readyz]
      interval: 5s
      retries: 3
    restart: unless-stopped

  cloudflare-tunnel:
    container_name: soft-serve_cloudflare-tunnel
    image: docker.io/cloudflare/cloudflared:2026.7.1@sha256:188bb03589a32affed3cf4d0590565ffe67b78866e6b5582574afab2b705bafe
    command: [tunnel, --no-autoupdate, run]
    environment:
      TUNNEL_TOKEN: $TUNNEL_TOKEN
    restart: unless-stopped

volumes:
  soft-serve:

configs:
  timezone:
    file: /etc/localtime
  git_config:
    file: ./config/.gitconfig
