name: soft-serve

services:
  server:
    container_name: soft-serve_server
    image: docker.io/charmcli/soft-serve:v0.12.2@sha256:554cc770ba8da5852ff51ead37146810f1d6f244d42f01f6f4d66ee44fbdf4d0
    init: true
    environment:
      SOFT_SERVE_INITIAL_ADMIN_KEYS: $SOFT_SERVE_INITIAL_ADMIN_KEYS
      SOFT_SERVE_NAME: $SOFT_SERVE_NAME
      SOFT_SERVE_SSH_PUBLIC_URL: ssh://$SOFT_SERVE_DOMAIN
    volumes:
      - soft-serve:/soft-serve
    configs:
      - source: timezone
        target: /etc/localtime
      - source: git_config
        target: /root/.gitconfig
    healthcheck:
      test: [CMD, wget, --spider, -q, http://localhost:23232/readyz]
      interval: 10s
      retries: 5
    restart: unless-stopped

  cloudflare-tunnel:
    container_name: soft-serve_cloudflare-tunnel
    image: docker.io/cloudflare/cloudflared:2026.8.3@sha256:51c9cefcb4569df44e1ad403ab1d3d8065aa8e84339bcfc6aee75502e1140339
    command: [tunnel, --no-autoupdate, run]
    environment:
      TUNNEL_TOKEN: $TUNNEL_TOKEN
    restart: unless-stopped

volumes:
  soft-serve:

configs:
  timezone:
    file: /etc/localtime
  git_config:
    file: ./config/.gitconfig
