#!/usr/bin/env bash

set -euo pipefail

domain="$1"
ssh -n "$domain" info >/dev/null
while read -r repo; do
  name="$(echo "$repo" | jq -r '.name')"
  url="$(echo "$repo" | jq '.url')"
  description="$(echo "$repo" | jq '.description')"

  echo "Importing $name..."
  ssh -n "$domain" repo import -m "$name" "$url" -d "$description" || :
  echo
done < <(gh repo list --source --json='name,description,url' --jq='.[]')
