name: 🔍 Detect Changed Compose Files
description: Detect changed compose files

inputs:
  workflow_file:
    description: GitHub Actions workflow file to run this action
    required: true

outputs:
  compose_files:
    description: Compose files that are changed
    value: ${{ steps.collect.outputs.compose_files }}

runs:
  using: composite

  steps:
    - name: 🔄 Filter changed files
      id: filter
      uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
      with:
        filters: |
          compose: "**/compose.yml"
          workflow: ${{ inputs.workflow_file }}
        list-files: shell

    - name: 📡 Collect compose information
      id: collect
      run: |
        if "$WORKFLOW_CHANGED"; then
          compose_files="$(find "$GITHUB_WORKSPACE" -name 'compose.yml')"
        else
          compose_files="$CHANGED_COMPOSE_FILES"
        fi
        for compose_file in $compose_files; do
          dir="$(dirname "$compose_file" | xargs basename)"
          name="$(grep -Po '(?<=<!-- name: ).+(?= -->)' "$dir/README.md")"
          echo "$name,$dir" | jq -Rc 'split(",") | { name: .[0], dir: .[1] }'
        done | echo "compose_files=$(jq -sc)" | tee -a "$GITHUB_OUTPUT"
      shell: bash
      env:
        CHANGED_COMPOSE_FILES: ${{ steps.filter.outputs.compose_files }}
        WORKFLOW_CHANGED: ${{ steps.filter.outputs.workflow }}
