name: 🔍 Detect Changed Compose
description: Detect changed compose

outputs:
  compose:
    description: Compose that are changed
    value: ${{ steps.collect.outputs.compose }}

runs:
  using: composite

  steps:
    - name: 🔄 Filter changed files
      id: filter
      uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
      with:
        filters: |
          compose:
            - added|modified: ["**/compose.yml", "**/config/**"]
        list-files: shell

    - name: 📡 Collect compose information
      id: collect
      run: |
        if [[ -z "$CHANGED_COMPOSE" ]]; then
          composes="$(find "$GITHUB_WORKSPACE" -name 'compose.yml' -exec dirname {} +)"
        else
          composes="$(echo "$CHANGED_COMPOSE" | sed -E 's/\/(compose\.yml|config\/.+)//g' | tr ' ' '\n' | sort | uniq)"
        fi
        while IFS= read -r compose; do
          dir="$(basename "$compose")"
          name="$(grep -Po '(?<=<!-- name: ).+(?= -->)' "$dir/README.md")"
          echo "$name,$dir" | jq -Rc 'split(",") | { name: .[0], dir: .[1] }'
        done <<<"$composes" | echo "compose=$(jq -sc)" | tee -a "$GITHUB_OUTPUT"
      shell: bash
      env:
        CHANGED_COMPOSE: ${{ steps.filter.outputs.compose_files }}
