name: 🔍 Detect Changed Compose
description: Detect changed compose

inputs:
  trigger_files:
    description: YAML formatted array of files to trigger all compose
    required: true

outputs:
  compose:
    description: Compose that are changed
    value: ${{ steps.collect.outputs.compose }}

runs:
  using: composite

  steps:
    - name: 🔄 Filter changed files
      id: filter
      uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
      with:
        filters: |
          compose: ["**/compose.yml", "**/config"]
          triggers: ${{ inputs.trigger_files }}
        list-files: shell

    - name: 📡 Collect compose information
      id: collect
      run: |
        if "$TRIGGER_CHANGED"; then
          composes="$(find "$GITHUB_WORKSPACE" -name 'compose.yml' | xargs dirname)"
        else
          composes="$(echo "$CHANGED_COMPOSE" | xargs dirname | sort | uniq)"
        fi
        for compose in $composes; do
          dir="$(basename "$compose")"
          name="$(grep -Po '(?<=<!-- name: ).+(?= -->)' "$dir/README.md")"
          echo "$name,$dir" | jq -Rc 'split(",") | { name: .[0], dir: .[1] }'
        done | echo "compose=$(jq -sc)" | tee -a "$GITHUB_OUTPUT"
      shell: bash
      env:
        CHANGED_COMPOSE: ${{ steps.filter.outputs.compose_files }}
        TRIGGER_CHANGED: ${{ steps.filter.outputs.triggers }}
