#!/usr/bin/env bash

set -euo pipefail

gh auth status >/dev/null
type jq >/dev/null

domain="$1"
ssh -n "$domain" info >/dev/null

(
  gh api /user/repos --paginate \
    --jq='.[] | select(.owner.type == "User" and (.fork | not)) |
      { name: .full_name, project: .full_name, description: .description, url: if .private then .ssh_url else .clone_url end, private: .private }'
  gh api /gists --paginate \
    --jq='.[] | { name: .id, project: .files | keys[0], description: .description, url: .git_pull_url, private: .public | not }'
) | while read -r repo; do
  name="$(jq -r '.name' <<<"$repo")"
  project="$(jq -r '.project' <<<"$repo")"
  description="$(jq -r '.description // empty' <<<"$repo")"
  url="$(jq -r '.url' <<<"$repo")"
  private="$(jq -r '.private' <<<"$repo")"

  if (ssh -n "$domain" repo branch list "$name" &>/dev/null); then
    echo "Skipped $project"
    continue
  fi

  echo "Importing $project..."
  ssh -fn "$domain" repo import "$name" "$url" -n="$project" "${description:+-d=\""$description"\"}" -mp="$private"
done
