name: speedtest-tracker

services:
  speedtest-tracker:
    container_name: speedtest-tracker
    image: docker.io/linuxserver/speedtest-tracker:1.13.10@sha256:4023b3e993d3764efe41d65eb4d1be8d9ff2ad8d756eb71de35fe805882ff0b5
    environment:
      APP_KEY: $APP_KEY
      DB_CONNECTION: pgsql
      DB_HOST: $DB_HOSTNAME
      DB_DATABASE: $DB_DATABASE_NAME
      DB_USERNAME: $DB_USERNAME
      DB_PASSWORD: $DB_PASSWORD
      SPEEDTEST_SCHEDULE: 0 * * * *
      SPEEDTEST_SERVERS: $SPEEDTEST_SERVERS
      DISPLAY_TIMEZONE: JST
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: curl -f http://localhost/api/healthcheck | jq -r .message || exit 1
      interval: 5s
      retries: 3
    restart: unless-stopped

  database:
    container_name: &speedtest-tracker_database speedtest-tracker_database
    image: docker.io/postgres:17.9@sha256:2cd82735a36356842d5eb1ef80db3ae8f1154172f0f653db48fde079b2a0b7f7
    environment:
      POSTGRES_HOST: $DB_HOSTNAME
      POSTGRES_DB: $DB_DATABASE_NAME
      POSTGRES_USER: $DB_USERNAME
      POSTGRES_PASSWORD: $DB_PASSWORD
    volumes:
      - database:/var/lib/postgresql/data
      - database-backup:/tmp/backup
    healthcheck:
      test: pg_isready -d '$DB_DATABASE_NAME' -U '$DB_USERNAME' || exit 1
      interval: 5s
      retries: 3
    labels:
      docker-volume-backup.exec-label: *speedtest-tracker_database
      docker-volume-backup.archive-pre: pg_dump -d '$DB_DATABASE_NAME' -U '$DB_USERNAME' -f /tmp/backup/speedtest-tracker.sql
    restart: unless-stopped

  backup:
    container_name: speedtest-tracker_backup
    image: docker.io/offen/docker-volume-backup:v2.47.2@sha256:23c9daf2529f1ffdc5db1911e424a613c618a14a75b2f20b1fe59ab282bbd271
    environment:
      BACKUP_CRON_EXPRESSION: 0 5 * * *
      BACKUP_FILENAME: speedtest-tracker_database_%Y%m%d.{{ .Extension }}
      AWS_S3_PATH: $R2_PATH/database
      BACKUP_SOURCES: &backup_database_source /backup/database
      BACKUP_ARCHIVE: &backup_database_archive /archive/database
      BACKUP_RETENTION_DAYS: 14
      GPG_PASSPHRASE: $DB_PASSWORD
      EXEC_LABEL: *speedtest-tracker_database
    env_file:
      - path: ../.env
        required: true
    volumes:
      - type: volume
        source: database-backup
        target: *backup_database_source
        read_only: true
      - type: bind
        source: $BACKUP_DIR/database
        target: *backup_database_archive
    configs:
      - source: docker-socket
        target: /var/run/docker.sock
      - source: timezone
        target: /etc/localtime
    depends_on:
      database:
        condition: service_healthy
    restart: unless-stopped

  cloudflare-tunnel:
    container_name: speedtest-tracker_cloudflare-tunnel
    image: docker.io/cloudflare/cloudflared:2026.2.0@sha256:404528c1cd63c3eb882c257ae524919e4376115e6fe57befca8d603656a91a4c
    command: tunnel --no-autoupdate run
    environment:
      TUNNEL_TOKEN: $TUNNEL_TOKEN
    restart: unless-stopped

volumes:
  database:
  database-backup:

configs:
  docker-socket:
    file: /var/run/docker.sock
  timezone:
    file: /etc/localtime
