name: speedtest-tracker

services:
  speedtest-tracker:
    container_name: speedtest-tracker
    image: docker.io/linuxserver/speedtest-tracker:1.14.5@sha256:ef562fc6b5e5922e50e13cc796bdc0a45fec7173e410473370fb9f2a4d8a9084
    environment:
      APP_KEY: $APP_KEY
      DB_CONNECTION: pgsql
      DB_HOST: $DB_HOSTNAME
      DB_DATABASE: $DB_DATABASE_NAME
      DB_USERNAME: $DB_USERNAME
      DB_PASSWORD: $DB_PASSWORD
      SPEEDTEST_SCHEDULE: "*/15 * * * *"
      DISPLAY_TIMEZONE: JST
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: [CMD, curl, -f, http://localhost/api/healthcheck]
      interval: 5s
      retries: 3
    restart: unless-stopped

  database:
    container_name: &speedtest-tracker_database speedtest-tracker_database
    image: docker.io/postgres:18.4@sha256:4aabea78cf39b90e834caf3af7d602a18565f6fe2508705c8d01aa63245c2e20
    environment:
      POSTGRES_HOST: $DB_HOSTNAME
      POSTGRES_DB: $DB_DATABASE_NAME
      POSTGRES_USER: $DB_USERNAME
      POSTGRES_PASSWORD: $DB_PASSWORD
    volumes:
      - database:/var/lib/postgresql
      - database-backup:/tmp/backup
    healthcheck:
      test: [CMD, pg_isready, -d, $DB_DATABASE_NAME, -U, $DB_USERNAME]
      interval: 5s
      retries: 3
    labels:
      docker-volume-backup.exec-label: *speedtest-tracker_database
      docker-volume-backup.archive-pre: pg_dump -d '$DB_DATABASE_NAME' -U '$DB_USERNAME' -f /tmp/backup/speedtest-tracker.sql
    restart: unless-stopped

  backup:
    container_name: speedtest-tracker_backup
    image: docker.io/offen/docker-volume-backup:v2.48.2@sha256:19102d8e59eb1d598cf8c647c2b21100abaadc5a1c808ac643fa612e323c3013
    environment:
      BACKUP_CRON_EXPRESSION: 0 5 * * *
      BACKUP_FILENAME: speedtest-tracker_database_%Y%m%d.{{ .Extension }}
      AWS_S3_PATH: $R2_PATH/database
      BACKUP_SOURCES: &backup_database_source /backup/database
      BACKUP_ARCHIVE: &backup_database_archive /archive/database
      BACKUP_RETENTION_DAYS: 14
      GPG_PASSPHRASE: $DB_PASSWORD
      EXEC_LABEL: *speedtest-tracker_database
    env_file:
      - path: ../.env
        required: true
    volumes:
      - type: volume
        source: database-backup
        target: *backup_database_source
        read_only: true
      - type: bind
        source: $BACKUP_DIR/database
        target: *backup_database_archive
    configs:
      - source: docker-socket
        target: /var/run/docker.sock
      - source: timezone
        target: /etc/localtime
    depends_on:
      database:
        condition: service_healthy
    restart: unless-stopped

  cloudflare-tunnel:
    container_name: speedtest-tracker_cloudflare-tunnel
    image: docker.io/cloudflare/cloudflared:2026.6.1@sha256:6d91c121b803126f7a5344005d17a9324788fc09d305b6e2560ec6040a7ae283
    command: [tunnel, --no-autoupdate, run]
    environment:
      TUNNEL_TOKEN: $TUNNEL_TOKEN
    restart: unless-stopped

volumes:
  database:
  database-backup:

configs:
  docker-socket:
    file: /var/run/docker.sock
  timezone:
    file: /etc/localtime
