name: paperless

services:
  webserver:
    container_name: paperless_webserver
    image: ghcr.io/paperless-ngx/paperless-ngx:2.20.15@sha256:6c86cad803970ea782683a8e80e7403444c5bf3cf70de63b4d3c8e87500db92f
    environment:
      PAPERLESS_REDIS: redis://redis:6379
      PAPERLESS_DBHOST: $DB_HOSTNAME
      PAPERLESS_DBNAME: $DB_DATABASE_NAME
      PAPERLESS_DBUSER: $DB_USERNAME
      PAPERLESS_DBPASS: $DB_PASSWORD
      PAPERLESS_FILENAME_FORMAT: "{{ created_year }}/{{ created_month }}-{{ created_day }}/{{ title }}"
      PAPERLESS_SECRET_KEY: $DB_PASSWORD
      PAPERLESS_URL: $PAPERLESS_URL
      PAPERLESS_OCR_LANGUAGE: jpn+eng
      PAPERLESS_OCR_LANGUAGES: jpn
    volumes:
      - ./media:/usr/src/paperless/media
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped

  database:
    container_name: &paperless_database paperless_database
    image: docker.io/postgres:18.4@sha256:1a5b3e745bbd82d6deb146505e504da3c2f248cac15e431951b148fbe4f8613a
    environment:
      POSTGRES_HOST: $DB_HOSTNAME
      POSTGRES_DB: $DB_DATABASE_NAME
      POSTGRES_USER: $DB_USERNAME
      POSTGRES_PASSWORD: $DB_PASSWORD
    volumes:
      - database:/var/lib/postgresql
      - database-backup:/tmp/backup
    healthcheck:
      test: [CMD, pg_isready, -d, $DB_DATABASE_NAME, -U, $DB_USERNAME]
      interval: 5s
      retries: 3
    labels:
      docker-volume-backup.exec-label: *paperless_database
      docker-volume-backup.archive-pre: pg_dump -d '$DB_DATABASE_NAME' -U '$DB_USERNAME' -f /tmp/backup/paperless.sql
    restart: unless-stopped

  redis:
    container_name: paperless_redis
    image: docker.io/redis:7.2.5-alpine3.19@sha256:8f157725f8eee31e65a8d4765f1f986d76aedc1a0503345dfb63a2b1b5a441ee
    healthcheck:
      test: [CMD, redis-cli, ping]
      interval: 5s
      retries: 3
    restart: unless-stopped

  backup:
    container_name: paperless_backup
    image: docker.io/offen/docker-volume-backup:v2.48.1@sha256:8c0b4ea09c72e7031de1256c07238af700d60b643eb6b27148bd4431871c0c7c
    environment:
      BACKUP_CRON_EXPRESSION: 0 5 * * *
      R2_PATH: $R2_PATH
      BACKUP_RETENTION_DAYS: 14
      GPG_PASSPHRASE: $DB_PASSWORD
    env_file:
      - path: ../.env
        required: true
    volumes:
      - database-backup:/backup/database:ro
      - $BACKUP_DIR/database:/archive/database
      - ./media/documents/originals:/backup/media:ro
      - $BACKUP_DIR/media:/archive/media
    configs:
      - source: docker-socket
        target: /var/run/docker.sock
      - source: timezone
        target: /etc/localtime
      - source: backup_config
        target: /etc/dockervolumebackup/conf.d
    depends_on:
      database:
        condition: service_healthy
    restart: unless-stopped

  cloudflare-tunnel:
    container_name: paperless_cloudflare-tunnel
    image: docker.io/cloudflare/cloudflared:2026.6.1@sha256:6d91c121b803126f7a5344005d17a9324788fc09d305b6e2560ec6040a7ae283
    command: [tunnel, --no-autoupdate, run]
    environment:
      TUNNEL_TOKEN: $TUNNEL_TOKEN
    restart: unless-stopped

volumes:
  database:
  database-backup:

configs:
  docker-socket:
    file: /var/run/docker.sock
  timezone:
    file: /etc/localtime
  backup_config:
    file: ./config/backup
