name: grafana

services:
  alloy:
    container_name: grafana_alloy
    image: docker.io/grafana/alloy:v1.17.1@sha256:4f6ddc56ffdcf8a6316748fc5162972e20cb301523cac1bb4a31957df733ae9b
    environment:
      GRAFANA_CLOUD_API_KEY: $GRAFANA_CLOUD_API_KEY
      PROMETHEUS_URL: $PROMETHEUS_URL
      PROMETHEUS_USERNAME: $PROMETHEUS_USERNAME
      LOKI_URL: $LOKI_URL
      LOKI_USERNAME: $LOKI_USERNAME
    volumes:
      - alloy:/var/lib/alloy/data
    configs:
      - source: docker-socket
        target: /var/run/docker.sock
      - source: system-bus-socket
        target: /run/dbus/system_bus_socket
      - source: rootfs
        target: /rootfs
      - source: sys
        target: /sys
      - source: proc
        target: /proc
      - source: run-log
        target: /run/log
      - source: var-log
        target: /var/log
      - source: hostname
        target: /etc/hostname
      - source: alloy_config
        target: /etc/alloy/config.alloy
    network_mode: host
    privileged: true
    healthcheck:
      test: [CMD, echo, GET /-/healthy, ">/dev/tcp/localhost/12345"]
      interval: 5s
      retries: 3
    depends_on:
      smartctl-exporter:
        condition: service_healthy
      cadvisor:
        condition: service_healthy
    restart: unless-stopped

  smartctl-exporter:
    container_name: grafana_smartctl-exporter
    image: docker.io/prometheuscommunity/smartctl-exporter:v0.14.0@sha256:cfe22c36d7d2fac48ebf619707305acb65eb0fb670656eb80f356e606d782bc1
    volumes:
      - /dev:/dev
    ports:
      - 9633:9633
    user: root
    privileged: true
    healthcheck:
      test: [CMD, wget, --spider, -q, http://localhost:9633/metrics]
      interval: 5s
      retries: 3
    restart: unless-stopped

  cadvisor:
    container_name: grafana_cadvisor
    image: gcr.io/cadvisor/cadvisor:v0.55.1@sha256:9cc0da1192a4d0cd3597d16cdc3c625b8cc5636cee201f3d122c8331e1a01069
    configs:
      - source: docker-socket
        target: /var/run/docker.sock
      - source: rootfs
        target: /rootfs
      - source: sys
        target: /sys
      - source: var-run
        target: /var/run
      - source: disk
        target: /dev/disk
    ports:
      - 8080:8080
    privileged: true
    healthcheck:
      test: [CMD, wget, --spider, -q, http://localhost:8080/healthz]
      interval: 5s
      retries: 3
    restart: unless-stopped

volumes:
  alloy:

configs:
  docker-socket:
    file: /var/run/docker.sock
  system-bus-socket:
    file: /run/dbus/system_bus_socket
  rootfs:
    file: /
  sys:
    file: /sys
  proc:
    file: /proc
  var-run:
    file: /var/run
  run-log:
    file: /run/log
  var-log:
    file: /var/log
  disk:
    file: /dev/disk
  hostname:
    file: /etc/hostname
  alloy_config:
    file: ./config/config.alloy
