name: timemachine

services:
  timemachine:
    container_name: timemachine
    image: docker.io/mbentley/timemachine:smb-20260802@sha256:333d42234c281acd7f1b40bb7458780b246de3dd4f568eca1ff36354760550f6
    environment:
      TM_USERNAME: $TM_USERNAME
      PASSWORD: $TM_PASSWORD
      SHARE_NAME: $TM_SHARE_NAME
      VOLUME_SIZE_LIMIT: $TM_VOLUME_SIZE_LIMIT
    volumes:
      - $BACKUP_DIR:/opt/$TM_USERNAME
    network_mode: host
    restart: unless-stopped
