name: homepage

services:
  homepage:
    container_name: homepage
    image: ghcr.io/gethomepage/homepage:v0.9.2@sha256:5356c97b51e3cc817bed93612b4e57b39d28048ab9e4e3b346e827160cf0923e
    env_file: [".env"]
    volumes:
      - ./config/homepage/settings.yml:/app/config/settings.yaml:ro
      - ./config/homepage/bookmarks.yml:/app/config/bookmarks.yaml:ro
      - ./config/homepage/services.yml:/app/config/services.yaml:ro
      - ./config/homepage/widgets.yml:/app/config/widgets.yaml:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /Volumes/Macintosh HD:/mnt/Macintosh HD:ro
    depends_on:
      - glances
      - tailscale
    network_mode: service:tailscale
    restart: always

  glances:
    container_name: homepage_glances
    image: nicolargo/glances:4.0.8@sha256:90bdf86cbff552051b134c8854e6e1a820143b0e031f9808ec112eb4686a5397
    environment:
      - "GLANCES_OPT=-w"
    pid: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/os-release:/etc/os-release:ro
    restart: always

  tailscale:
    container_name: homepage_tailscale
    hostname: homepage
    image: tailscale/tailscale:v1.68.1@sha256:a0d1a9ed2abfacf905c0e3423aea00181064162e548f875f422a03924b9cc5c4
    env_file: [".env"]
    environment:
      TS_STATE_DIR: /var/lib/tailscale
      TS_SERVE_CONFIG: /config/tailscale.json
    volumes:
      - tailscale-state:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
      - ./config/tailscale.json:/config/tailscale.json:ro
    cap_add:
      - net_admin
      - sys_module
    restart: always

volumes:
  tailscale-state:
