name: immich

services:
  server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:v2.7.5@sha256:c15bff75068effb03f4355997d03dc7e0fc58720c2b54ad6f7f10d1bc57efaa5
    environment:
      IMMICH_CONFIG_FILE: &immich_config /config/immich.json
      DB_HOSTNAME: $DB_HOSTNAME
      DB_DATABASE_NAME: $DB_DATABASE_NAME
      DB_USERNAME: $DB_USERNAME
      DB_PASSWORD: $DB_PASSWORD
    volumes:
      - type: bind
        source: ./data
        target: &data /data
    configs:
      - source: timezone
        target: /etc/localtime
      - source: immich_config
        target: *immich_config
    post_start:
      - command: bash -c '
          mkdir -p upload library thumbs encoded-video profile backups &&
          touch {upload,library,thumbs,encoded-video,profile,backups}/.immich'
        working_dir: *data
    depends_on:
      machine-learning:
        condition: service_healthy
      database:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped

  machine-learning:
    container_name: immich_machine-learning
    image: ghcr.io/immich-app/immich-machine-learning:v2.7.5@sha256:a2501141440f10516d329fdfba2c68082e19eb9ba6016c061ac80d23beadf7f3
    volumes:
      - model-cache:/cache
    restart: unless-stopped

  database:
    container_name: &immich_database immich_database
    image: ghcr.io/immich-app/postgres:18-vectorchord0.5.3-pgvector0.8.1@sha256:ef431845dc61cdc061a2f2ff2ba927e87868e10ffd3d7e689a79fba061b043c0
    environment:
      POSTGRES_HOST: $DB_HOSTNAME
      POSTGRES_DB: $DB_DATABASE_NAME
      POSTGRES_USER: $DB_USERNAME
      POSTGRES_PASSWORD: $DB_PASSWORD
    volumes:
      - database:/var/lib/postgresql
      - database-backup:/tmp/backup
    labels:
      docker-volume-backup.exec-label: *immich_database
      docker-volume-backup.archive-pre: pg_dump -d '$DB_DATABASE_NAME' -U '$DB_USERNAME' -f /tmp/backup/immich.sql
    restart: unless-stopped

  redis:
    container_name: immich_redis
    image: docker.io/redis:7.2.5-alpine3.19@sha256:8f157725f8eee31e65a8d4765f1f986d76aedc1a0503345dfb63a2b1b5a441ee
    healthcheck:
      test: [CMD, redis-cli, ping]
      interval: 5s
      retries: 3
    restart: unless-stopped

  backup:
    container_name: immich_backup
    image: docker.io/offen/docker-volume-backup:v2.48.0@sha256:8eaf987d83e7b5f7c4edd8d177c2ca74b49a0d015d241e99a260c19a043b46aa
    environment:
      BACKUP_CRON_EXPRESSION: 0 5 * * *
      R2_PATH: $R2_PATH
      BACKUP_RETENTION_DAYS: 14
      GPG_PASSPHRASE: $DB_PASSWORD
    env_file:
      - path: ../.env
        required: true
    volumes:
      - database-backup:/backup/database:ro
      - $BACKUP_DIR/database:/archive/database
      - ./data/library:/backup/data/library:ro
      - ./data/profile:/backup/data/profile:ro
      - $BACKUP_DIR/data:/archive/data
    configs:
      - source: docker-socket
        target: /var/run/docker.sock
      - source: timezone
        target: /etc/localtime
      - source: backup_config
        target: /etc/dockervolumebackup/conf.d
    depends_on:
      database:
        condition: service_healthy
    restart: unless-stopped

  cloudflare-tunnel:
    container_name: immich_cloudflare-tunnel
    image: docker.io/cloudflare/cloudflared:2026.3.0@sha256:6b599ca3e974349ead3286d178da61d291961182ec3fe9c505e1dd02c8ac31b0
    command: [tunnel, --no-autoupdate, run]
    environment:
      TUNNEL_TOKEN: $TUNNEL_TOKEN
    restart: unless-stopped

volumes:
  model-cache:
  database:
  database-backup:

configs:
  docker-socket:
    file: /var/run/docker.sock
  timezone:
    file: /etc/localtime
  immich_config:
    file: ./config/immich.json
  backup_config:
    file: ./config/backup
