name: adguard

services:
  home:
    container_name: adguard_home
    image: docker.io/adguard/adguardhome:v0.107.79@sha256:aba9e3bf0613be3ba3755e1fc311b126e2c24bec25e18b6483894a88283074f0
    volumes:
      - work:/opt/adguardhome/work
      - ./config/adguard:/opt/adguardhome/conf
    healthcheck:
      test:
        [
          CMD-SHELL,
          nslookup example.com 127.0.0.1 || wget --spider -q http://localhost:3000,
        ]
      interval: 10s
      retries: 5
    restart: unless-stopped

  backup:
    container_name: adguard_backup
    image: docker.io/offen/docker-volume-backup:v2.48.2@sha256:19102d8e59eb1d598cf8c647c2b21100abaadc5a1c808ac643fa612e323c3013
    environment:
      BACKUP_CRON_EXPRESSION: 0 5 * * *
      R2_PATH: $R2_PATH
      BACKUP_RETENTION_DAYS: 14
      GPG_PASSPHRASE: $PASSPHRASE
      TZ: Asia/Tokyo
    env_file:
      - path: ../.env
        required: true
    volumes:
      - work:/backup/work:ro
      - $BACKUP_DIR/work:/archive/work
      - ./config/adguard:/backup/config:ro
      - $BACKUP_DIR/config:/archive/config
    configs:
      - source: backup_config
        target: /etc/dockervolumebackup/conf.d
    depends_on:
      home:
        condition: service_healthy
    restart: unless-stopped

  cloudflare-tunnel:
    container_name: adguard_cloudflare-tunnel
    image: docker.io/cloudflare/cloudflared:2026.8.2@sha256:0aa26e284f05e6c77ae375b8c9c11d9eb6a448fb7bcd8d40f31cb6176189eb38
    command: [tunnel, --no-autoupdate, run]
    environment:
      TUNNEL_TOKEN: $TUNNEL_TOKEN
    restart: unless-stopped

volumes:
  work:

configs:
  backup_config:
    file: ./config/backup
