- Machine:
    - System Info:
        widget:
          type: glances
          url: http://glances:61208
          version: 4
          metric: info
    - Processes:
        widget:
          type: glances
          url: http://glances:61208
          version: 4
          metric: process
    - CPU Usage:
        widget:
          type: glances
          url: http://glances:61208
          version: 4
          metric: cpu
    - Memory Usage:
        widget:
          type: glances
          url: http://glances:61208
          version: 4
          metric: memory
    - Network:
        widget:
          type: glances
          url: http://glances:61208
          version: 4
          metric: network:eth0
    - Disk I/O:
        widget:
          type: glances
          url: http://glances:61208
          version: 4
          metric: disk:vdb1
