- Media:
    - Immich:
        icon: immich
        href: "{{HOMEPAGE_VAR_IMMICH_HOST}}"
        description: Self-hosted photo and video management solution
        ping: "{{HOMEPAGE_VAR_IMMICH_HOST}}"
        container: immich
        widget:
          type: immich
          url: "{{HOMEPAGE_VAR_IMMICH_HOST}}"
          key: "{{HOMEPAGE_VAR_IMMICH_API_KEY}}"

- Souma's MacBook Pro:
    - System Info:
        widget:
          type: glances
          url: http://glances:61208
          version: 4
          metric: info
    - Processes:
        widget:
          type: glances
          url: http://glances:61208
          version: 4
          metric: process
    - CPU Usage:
        widget:
          type: glances
          url: http://glances:61208
          version: 4
          metric: cpu
    - Memory Usage:
        widget:
          type: glances
          url: http://glances:61208
          version: 4
          metric: memory
    - Network:
        widget:
          type: glances
          url: http://glances:61208
          version: 4
          metric: network:eth0
    - Disk I/O:
        widget:
          type: glances
          url: http://glances:61208
          version: 4
          metric: disk:vdb1
