name: 🔍 Detect Compose Files
description: Detect changed compose files

inputs:
  workflow:
    description: GitHub Action Workflow to run this action
    required: true

outputs:
  composes:
    description: Compose files that are changed
    value: ${{ steps.detect.outputs.composes }}

runs:
  using: composite

  steps:
    - name: 🔄 Filter the Changed Files
      id: filter
      uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
      with:
        filters: |
          compose: "**/compose.yml"
          workflow: ${{ inputs.workflow }}
        list-files: shell

    - name: 📡 Collect the Compose Information
      id: detect
      env:
        WORKFLOW_CHANGED: ${{ steps.filter.outputs.workflow }}
        CHANGED_COMPOSE_FILES: ${{ steps.filter.outputs.compose_files }}
      run: |
        if "$WORKFLOW_CHANGED"; then
          composes="$(find "$GITHUB_WORKSPACE" -name 'compose.yml')"
        else
          composes="$CHANGED_COMPOSE_FILES"
        fi
        for compose in $composes; do
          dir="$(dirname "$compose" | xargs basename)"
          name="$(grep -Po '(?<=<!-- name: ).+(?= -->)' "$dir/README.md")"
          echo "$name,$dir" | jq -Rc 'split(",") | { name: .[0], dir: .[1] }'
        done | echo "composes=$(jq -sc)" | tee -a "$GITHUB_OUTPUT"
      shell: bash
