name: 🧪 Test

on:
  push:
    branches:
      - main
    paths:
      - "**/compose.yml"
      - "**/config/**"
      - .github/workflows/test.yml
      - .env.tmpl
  pull_request:
    paths:
      - "**/compose.yml"
      - "**/config/**"
      - .github/workflows/test.yml
      - .env.tmpl

permissions: {}

jobs:
  detect:
    name: 🔍 Detect Changed Compose Files
    runs-on: Ubuntu-Slim
    timeout-minutes: 1
    outputs:
      compose: ${{ steps.detect.outputs.compose }}

    steps:
      - name: 🚚 Check out repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: 🔍 Detect changed compose files
        id: detect
        uses: ./.github/actions/detect-changed-compose

  test:
    name: ${{ matrix.compose.name }}
    needs: detect
    runs-on: Ubuntu-Latest
    defaults:
      run:
        working-directory: ${{ matrix.compose.dir }}
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        compose: ${{ fromJson(needs.detect.outputs.compose) }}

    steps:
      - name: 🚚 Check out repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: ♻️ Copy .env
        run: |
          for dir in "$PWD" "$GITHUB_WORKSPACE"; do
            sed \
              -e 's@_URL=$@_URL=http://example.com@' \
              -e 's/=$/=./g' \
              "$dir/.env.tmpl" >"$dir/.env"
          done

      - name: 🐳 Start containers
        run: docker compose up --quiet-pull --wait
